//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaBeatChartEditer.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HexaBeatChartEditer.Localization.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エクスポートに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集中のデータは破棄されますがよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDiscardConfirmation {
            get {
                return ResourceManager.GetString("FileDiscardConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの読み込み中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileLoadError {
            get {
                return ResourceManager.GetString("FileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルにアクセスできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotAccessible {
            get {
                return ResourceManager.GetString("FileNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のバージョンでは開けないファイルです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotCompatible {
            get {
                return ResourceManager.GetString("FileNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   古いバージョンで作成されたファイルです。
        ///バージョンアップしてよろしいですか？
        ///(以前のバージョンでは開けなくなります。) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileUpgradeNeeded {
            get {
                return ResourceManager.GetString("FileUpgradeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   譜面プロパティから音源ファイルを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MusicSourceNull {
            get {
                return ResourceManager.GetString("MusicSourceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputPathRequired {
            get {
                return ResourceManager.GetString("OutputPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグインの実行中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PluginException {
            get {
                return ResourceManager.GetString("PluginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のプラグインの読み込みに失敗しました。DLLファイルがブロックされている可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PluginLoadError {
            get {
                return ResourceManager.GetString("PluginLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PreviewException {
            get {
                return ResourceManager.GetString("PreviewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   簡易プレビューが利用できない環境です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PreviewNotSupported {
            get {
                return ResourceManager.GetString("PreviewNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再エクスポートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReExportComplete {
            get {
                return ResourceManager.GetString("ReExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音源ファイルが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SourceFileNotFound {
            get {
                return ResourceManager.GetString("SourceFileNotFound", resourceCulture);
            }
        }
    }
}
